#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# SSH agent
eval "$(keychain --eval --quiet --immediate id_ed25519_github)"

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vi='vim'
alias v='vim'

PS1='\[\e[0;32m\]\u@\h\[\e[0m\] \[\e[0;33m\]\w\[\e[0m\]\$ '
